# Use the official Python image as base.
FROM python:3.9-slim

# Set the working directory in the container.
WORKDIR /app

# Copy the current directory contents into the container at /app.
COPY . .

# Install any needed dependencies specified in requirements.txt.
RUN pip install flask

# Expose the port the app runs on.
EXPOSE 5000

# Run the Flask application.
CMD ["python", "app.py"]
